/*
 * This file is generated by jOOQ.
 */
package com.github.shipopotamus.authentication.adapters.jooq.model;


import com.github.shipopotamus.authentication.adapters.jooq.model.tables.Accounts;
import com.github.shipopotamus.authentication.adapters.jooq.model.tables.AuthenticationMethods;
import com.github.shipopotamus.authentication.adapters.jooq.model.tables.EmailPasswordAuthentications;
import com.github.shipopotamus.authentication.adapters.jooq.model.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthenticationSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>authentication_schema</code>
     */
    public static final AuthenticationSchema AUTHENTICATION_SCHEMA = new AuthenticationSchema();

    /**
     * The table <code>authentication_schema.accounts</code>.
     */
    public final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>authentication_schema.authentication_methods</code>.
     */
    public final AuthenticationMethods AUTHENTICATION_METHODS = AuthenticationMethods.AUTHENTICATION_METHODS;

    /**
     * The table
     * <code>authentication_schema.email_password_authentications</code>.
     */
    public final EmailPasswordAuthentications EMAIL_PASSWORD_AUTHENTICATIONS = EmailPasswordAuthentications.EMAIL_PASSWORD_AUTHENTICATIONS;

    /**
     * The table <code>authentication_schema.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private AuthenticationSchema() {
        super("authentication_schema", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Accounts.ACCOUNTS,
            AuthenticationMethods.AUTHENTICATION_METHODS,
            EmailPasswordAuthentications.EMAIL_PASSWORD_AUTHENTICATIONS,
            Users.USERS
        );
    }
}
