/*
 * This file is generated by jOOQ.
 */
package com.github.shipopotamus.authentication.adapters.jooq.model;


import com.github.shipopotamus.authentication.adapters.jooq.model.tables.Accounts;
import com.github.shipopotamus.authentication.adapters.jooq.model.tables.AuthenticationMethods;
import com.github.shipopotamus.authentication.adapters.jooq.model.tables.EmailPasswordAuthentications;
import com.github.shipopotamus.authentication.adapters.jooq.model.tables.Users;


/**
 * Convenience access to all tables in authentication_schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>authentication_schema.accounts</code>.
     */
    public static final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>authentication_schema.authentication_methods</code>.
     */
    public static final AuthenticationMethods AUTHENTICATION_METHODS = AuthenticationMethods.AUTHENTICATION_METHODS;

    /**
     * The table
     * <code>authentication_schema.email_password_authentications</code>.
     */
    public static final EmailPasswordAuthentications EMAIL_PASSWORD_AUTHENTICATIONS = EmailPasswordAuthentications.EMAIL_PASSWORD_AUTHENTICATIONS;

    /**
     * The table <code>authentication_schema.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
